version: '3.7'
services:
  mongo:
    image: mongo:4.1
  su:
    build: .
    command: sh -c "/wait && node bin/su.js"
    links:
    - mongo
    environment:
      PORT: 3000
      PUBLIC_URL: 'http://localhost:3000'
      MONGO_CS: 'mongodb://mongo/su_development'
      WAIT_HOSTS: mongo:27017
    ports:
    - "3000:3000"
    expose:
    - "3000"
